/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.FuncionarioDAO;
import javax.swing.JOptionPane;
import model.Funcionario;
import util.TelaUtils;

/**
 *
 * @author Ectho
 */

    /**
     * Classe que representa a tela de atualização de dados do funcionário.
     * 
     * Esta tela permite a modificação de informações associadas a um funcionário,
     * sendo inicializada sem dados prévios. Os dados do funcionário a serem
     * atualizados podem ser recebidos de outra tela.
     */
public class TelaUpdateFuncionario extends javax.swing.JFrame {

    // recebe os dados de uma outra tela
    Funcionario obj = null;
    
    /**
     * Construtor da classe. Inicializa os componentes gráficos da tela e
     * configura a tela para não ser redimensionável.
     */
    public TelaUpdateFuncionario() {
        initComponents();
        setResizable(false);
    }
    
    /**
    * Construtor da classe que recebe um objeto Funcionario a ser alterado e inicializa
    * os componentes gráficos da tela. Configura a tela para não ser redimensionável.
    * 
    * @param objAlterar Objeto Funcionario a ser modificado.
    */
    public TelaUpdateFuncionario(Funcionario objAlterar) {
        initComponents();
        setResizable(false);
        
        this.obj = objAlterar;
        
        // passar os valores do objeto para a tela
        lblIdFuncionario.setText(String.valueOf(obj.getIdFuncionario()));
        txtNomeCompletoFuncionario.setText(String.valueOf(obj.getNome()));
        //ftxtDataNascimentoFuncionario.setText(String.valueOf(obj.getDataNascimento()));
        cboxSexoFuncionario.setSelectedIndex(obj.getIndiceSexoFuncionario());
        ftxtCPFFuncionario.setText(String.valueOf(obj.getCpf()));
        cbxCargoFuncionario.setSelectedIndex(obj.getIndiceCargoFuncionario());
        txtSalarioVendedor.setText(String.valueOf(obj.getSalario()));
        cbxHorarioDeTrabalhoFuncionario.setSelectedIndex(obj.getIndiceHorarioDeTrabalhoFuncionario());
        
        String dataNascimento = obj.getDataNascimento();
        dataNascimento = dataNascimento.replace("-", ""); // Remove os traços
        
        ftxtDataNascimentoFuncionario.setText(String.valueOf(dataNascimento));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeCompletoFuncionario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ftxtDataNascimentoFuncionario = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ftxtCPFFuncionario = new javax.swing.JFormattedTextField();
        cboxSexoFuncionario = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        cbxCargoFuncionario = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtSalarioVendedor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbxHorarioDeTrabalhoFuncionario = new javax.swing.JComboBox<>();
        btnAtualizarFuncionario2 = new javax.swing.JButton();
        btnCancelarAtualizacaoFuncionario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblIdFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Atualizar Funcionario"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Pessoais"));

        jLabel1.setText("Nome Completo:");

        jLabel2.setText("Data de nascimento:");

        try {
            ftxtDataNascimentoFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDataNascimentoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftxtDataNascimentoFuncionarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Sexo:");

        jLabel4.setText("CPF:");

        try {
            ftxtCPFFuncionario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cboxSexoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Outros" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftxtCPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeCompletoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtDataNascimentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxSexoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeCompletoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ftxtDataNascimentoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboxSexoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftxtCPFFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Informações Profissionais"));

        jLabel12.setText("Cargo:");

        cbxCargoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Vendedor" }));
        cbxCargoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCargoFuncionarioActionPerformed(evt);
            }
        });

        jLabel13.setText("Salario:");

        jLabel14.setText("Horário de trabalho");

        cbxHorarioDeTrabalhoFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSalarioVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxHorarioDeTrabalhoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cbxCargoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtSalarioVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbxHorarioDeTrabalhoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnAtualizarFuncionario2.setText("Atualizar");
        btnAtualizarFuncionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarFuncionario2ActionPerformed(evt);
            }
        });

        btnCancelarAtualizacaoFuncionario.setText("Cancelar");
        btnCancelarAtualizacaoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAtualizacaoFuncionarioActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        lblIdFuncionario.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAtualizarFuncionario2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(btnCancelarAtualizacaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(104, 104, 104))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblIdFuncionario)
                                .addGap(212, 212, 212))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblIdFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizarFuncionario2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarAtualizacaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftxtDataNascimentoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtDataNascimentoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtDataNascimentoFuncionarioActionPerformed

    private void cbxCargoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCargoFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCargoFuncionarioActionPerformed

    private void btnAtualizarFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarFuncionario2ActionPerformed
        // Resgatar dados da interface e passar para o objeto
        String nomeFuncionario = txtNomeCompletoFuncionario.getText();
        String dataNascimento = ftxtDataNascimentoFuncionario.getText();
        int sexoSelecionado = cboxSexoFuncionario.getSelectedIndex() + 1; // Adicionar 1 para corresponder aos IDs (que começam em 1) // Sexo Funcionario
        String CPF = ftxtCPFFuncionario.getText();
        // Informações profissionais
        int cargoFuncionario = cbxCargoFuncionario.getSelectedIndex() + 1;
        double salarioVendedor = Double.parseDouble(txtSalarioVendedor.getText());
        int horarioDeTrabalho = cbxHorarioDeTrabalhoFuncionario.getSelectedIndex() + 1;
        
        validarAlgoNoCbox(sexoSelecionado);
        validarAlgoNoCbox(cargoFuncionario);
        validarAlgoNoCbox(horarioDeTrabalho);
        
        obj.setNome(nomeFuncionario);
        obj.setDataNascimento(dataNascimento);
        obj.setSexo(sexoSelecionado);
        obj.setCpf(CPF);
        obj.setCargo(cargoFuncionario);
        obj.setSalario(salarioVendedor);
        obj.setPeriodo(horarioDeTrabalho);
        
        // TODO: chamar a DAO para alterar o banco
        boolean retorno = FuncionarioDAO.alterar(obj);
        
        if (retorno){
            JOptionPane.showMessageDialog(rootPane, "Sucesso! Produto atualizado.");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Não foi possivel atualizar o produto. Tente Novamente!");
        }
        // fecha a tela de alteração
        this.dispose();
    }//GEN-LAST:event_btnAtualizarFuncionario2ActionPerformed

    private void btnCancelarAtualizacaoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAtualizacaoFuncionarioActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarAtualizacaoFuncionarioActionPerformed
    
    /**
    * Esta função valida um ComboBox, fornecendo uma maneira simplificada de verificar sua seleção
    * sem duplicar código. Recebe a variável do ComboBox e imprime informações no console.
    *
    * @param cboxVariavel O valor do ComboBox a ser validado.
    */
    private void validarAlgoNoCbox(int cboxVariavel){
        if (cboxVariavel > 0) {
            // Faça algo com a variável idCategoriaProduto
            System.out.println("Item selecionado: " + cboxVariavel);
        } else {
            System.out.println("Nenhuma item selecionado.");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUpdateFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUpdateFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUpdateFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUpdateFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUpdateFuncionario().setVisible(true);
            }
        });
    }
    
    /**
    * Classe que representa a tela de atualização de dados do funcionário.
    * 
    * Esta tela permite a modificação de informações associadas a um funcionário,
    * utilizando campos de entrada e outros componentes gráficos.
    * 
    * Os componentes gráficos incluem botões para atualizar e cancelar a atualização,
    * campos de seleção para o sexo, cargo e horário de trabalho do funcionário,
    * campos de texto formatado para CPF e data de nascimento, rótulos descritivos,
    * e campos de texto para o nome completo e salário do funcionário.
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarFuncionario2;
    private javax.swing.JButton btnCancelarAtualizacaoFuncionario;
    private javax.swing.JComboBox<String> cboxSexoFuncionario;
    private javax.swing.JComboBox<String> cbxCargoFuncionario;
    private javax.swing.JComboBox<String> cbxHorarioDeTrabalhoFuncionario;
    private javax.swing.JFormattedTextField ftxtCPFFuncionario;
    private javax.swing.JFormattedTextField ftxtDataNascimentoFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblIdFuncionario;
    private javax.swing.JTextField txtNomeCompletoFuncionario;
    private javax.swing.JTextField txtSalarioVendedor;
    // End of variables declaration//GEN-END:variables
}
